import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faPhone,
  faEnvelope,
  faShareNodes,
  faCheck,
  faStar,
  faCheckCircle,
  faDownload,
  faGlobe,
  faHeart,
  faUser,
  faHome,
  faSearch,
  faBars,
  faTimes,
  faPlus,
  faMinus,
  faEdit,
  faTrash,
  faSave,
  faEye,
  faEyeSlash,
  faLock,
  faUnlock,
  faCalendar,
  faClock,
  faMapMarkerAlt,
  faImage,
  faFile,
  faFolder,
  faLink,
  faExternalLinkAlt,
  faArrowUp,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faChevronUp,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faPlay,
  faPause,
  faStop,
  faVolumeUp,
  faVolumeDown,
  faVolumeMute,
  faThumbsUp,
  faThumbsDown,
  faComment,
  faComments,
  faShare,
  faBookmark,
  faFlag,
  faExclamationTriangle,
  faInfo,
  faQuestion,
  faExclamation,
  faTimesCircle,
  faExclamationCircle,
  faQuestionCircle,
  faInfoCircle,
  faBan,
  faCog,
  faWrench,
  faShieldAlt,
  faKey,
  faFingerprint,
  faCreditCard,
  faMoneyBillWave,
  faDollarSign,
  faEuroSign,
  faPoundSign,
  faYenSign,
} from "@fortawesome/free-solid-svg-icons";
import { icon } from "@fortawesome/fontawesome-svg-core";

// Add icons to the library
library.add(
  faPhone,
  faEnvelope,
  faShareNodes,
  faCheck,
  faStar,
  faCheckCircle,
  faDownload,
  faGlobe,
  faHeart,
  faUser,
  faHome,
  faSearch,
  faBars,
  faTimes,
  faPlus,
  faMinus,
  faEdit,
  faTrash,
  faSave,
  faEye,
  faEyeSlash,
  faLock,
  faUnlock,
  faCalendar,
  faClock,
  faMapMarkerAlt,
  faImage,
  faFile,
  faFolder,
  faLink,
  faExternalLinkAlt,
  faArrowUp,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faChevronUp,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faPlay,
  faPause,
  faStop,
  faVolumeUp,
  faVolumeDown,
  faVolumeMute,
  faThumbsUp,
  faThumbsDown,
  faComment,
  faComments,
  faShare,
  faBookmark,
  faFlag,
  faExclamationTriangle,
  faInfo,
  faQuestion,
  faExclamation,
  faTimesCircle,
  faExclamationCircle,
  faQuestionCircle,
  faInfoCircle,
  faBan,
  faCog,
  faWrench,
  faShieldAlt,
  faKey,
  faFingerprint,
  faCreditCard,
  faMoneyBillWave,
  faDollarSign,
  faEuroSign,
  faPoundSign,
  faYenSign
);

// Font Awesome SVG icons mapping using official package
export const createFontAwesomeSVG = (iconName, isBrand = false) => {
  console.log(
    "createFontAwesomeSVG called with:",
    iconName,
    "isBrand:",
    isBrand
  );

  const iconMap = {
    phone: faPhone,
    envelope: faEnvelope,
    "share-nodes": faShareNodes,
    check: faCheck,
    star: faStar,
    "check-circle": faCheckCircle,
    download: faDownload,
    globe: faGlobe,
    heart: faHeart,
    user: faUser,
    home: faHome,
    search: faSearch,
    bars: faBars,
    times: faTimes,
    plus: faPlus,
    minus: faMinus,
    edit: faEdit,
    trash: faTrash,
    save: faSave,
    eye: faEye,
    "eye-slash": faEyeSlash,
    lock: faLock,
    unlock: faUnlock,
    calendar: faCalendar,
    clock: faClock,
    "map-marker-alt": faMapMarkerAlt,
    image: faImage,
    file: faFile,
    folder: faFolder,
    link: faLink,
    "external-link-alt": faExternalLinkAlt,
    "arrow-up": faArrowUp,
    "arrow-down": faArrowDown,
    "arrow-left": faArrowLeft,
    "arrow-right": faArrowRight,
    "chevron-up": faChevronUp,
    "chevron-down": faChevronDown,
    "chevron-left": faChevronLeft,
    "chevron-right": faChevronRight,
    play: faPlay,
    pause: faPause,
    stop: faStop,
    "volume-up": faVolumeUp,
    "volume-down": faVolumeDown,
    "volume-mute": faVolumeMute,
    "thumbs-up": faThumbsUp,
    "thumbs-down": faThumbsDown,
    comment: faComment,
    comments: faComments,
    share: faShare,
    bookmark: faBookmark,
    flag: faFlag,
    "exclamation-triangle": faExclamationTriangle,
    info: faInfo,
    question: faQuestion,
    exclamation: faExclamation,
    "times-circle": faTimesCircle,
    "exclamation-circle": faExclamationCircle,
    "question-circle": faQuestionCircle,
    "info-circle": faInfoCircle,
    ban: faBan,
    cog: faCog,
    wrench: faWrench,
    "shield-alt": faShieldAlt,
    key: faKey,
    fingerprint: faFingerprint,
    "credit-card": faCreditCard,
    "money-bill-wave": faMoneyBillWave,
    "dollar-sign": faDollarSign,
    "euro-sign": faEuroSign,
    "pound-sign": faPoundSign,
    "yen-sign": faYenSign,
  };

  const iconDefinition = iconMap[iconName];
  if (!iconDefinition) {
    console.log(
      "createFontAwesomeSVG result for",
      iconName,
      ": FAILED - Icon not found"
    );
    return null;
  }

  // Generate SVG string from Font Awesome icon
  const svgString = icon(iconDefinition).html[0];
  console.log("createFontAwesomeSVG result for", iconName, ": SUCCESS");

  return svgString;
};
